#!/usr/bin/env bash

# maze-game – Maze solving game
# 
# Copyright © 2012, 2013  Mattias Andrée (maandree@member.fsf.org)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


echo -en '\e[?1049h'
stty -icanon -echo
echo -en '\e[?25l'
java  -jar "$0".jar "$@" 2>/tmp/.maze-game
rc=$?
echo -en '\e[?25h'
stty icanon echo
echo -en '\e[?1049l'
cat /tmp/.maze-game
rm  /tmp/.maze-game
exit $rc
